### ISSUE TITLE
Is there any version for drupal8

### ISSUE THREAD

**Issue by zexperto** [tawk/tawk-drupal#3]

**Comment by Rar9** [comment]
Any update for Drupal 8 soon? it should not be this hard to migrate from d7 to d8.

**Comment by beautifulmind** [comment]
Are you going to port this to Drupal8? Or would you be fine with anyone who attempt to do so?

**Comment by llanverygranger** [comment]
Any further news on Drupal 8? One of your customer service people said a Drupal 8 port was available? Thanks.

**Update:** I've just found this: [https://www.drupal.org/project/tawk_to](https://www.drupal.org/project/tawk_to)

**Comment by llanverygranger** [comment]
Even easier in the end... I just added a custom block that contained the javascript (make sure the block is set to take Full HTML and you enter it as source, not content.

**Comment by alvinjohnsonso** [comment]
Hi! This repository is only for Drupal 7. For Drupal 8, you can see https://github.com/tawk/tawk-drupal8.

The plugin for Drupal 8 is also available here in https://www.drupal.org/project/tawkto and there will be an update for Drupal 9 compatibility support.
